config/routes.rb
Rails.application.routes.draw do

  get 'event_dates/create'

  get 'invitees/index'

  get 'invitees/edit'

  get 'invitees/new'
  
  get '/event/:title' => 'events#show', as: :event

  root to: "top#login"

  require 'active_record/base'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "authed/index", as: "user_root"

  resources :events ,param: :title
  resources :events do
    
    resources :invitees,only: [:create,:destroy]
    resources :bars,param: :name
    resources :invitees
  end

  resources :userpages

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/
  belongs_to :event
  def self.barAdd(param,event_id)
        bar = Bar.create(
            name:    param["name"],
            url:     param["url"],
            good:   param["good"],
            bad:      param["bad"],
            event_id: event_id
            #userid:   uid
          )
  end

end

app/models/barelection.rb
class Barelection < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :invitees,      dependent: :destroy
  accepts_nested_attributes_for :invitees, :allow_destroy => true
  has_many :bars
  has_many :event_dates, :dependent => :destroy
  accepts_nested_attributes_for :event_dates

  validates :title, presence: true , uniqueness: true
  validates :detail, presence: true


    def self.eventAdd(param,uid)
          event = Event.create(
              title:    param["title"],
              date:     param["date"],
              detail:   param["detail"],
              userid:   uid
            )

    end
    
    def to_param
      return title
    end
end

app/models/event_date.rb
class EventDate < ActiveRecord::Base
    belongs_to :event
    validates :date, presence: true
end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
 
  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first
 
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # 常にログインを要求する
  #before_action :authenticate_user!
  before_action :authenticate_user!, except: :login
end

app/controllers/authed_controller.rb
class AuthedController < ApplicationController
    layout 'application'
    def index
      @events = Event.all

    end


end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  layout 'application'
  before_action :set_bar, only:[:show,:edit,:update,:destroy]
  def index
      @bars = Bar.all

      eventid = params[:event_id]
      sql = "SELECT * FROM bars;"
      results = ActiveRecord::Base.connection.execute(sql)

      p results

      @bar_tmp = Array.new

      #ログイン中のユーザのUIDに合致するものだけ投げる
      results.each{ |bar|
        p bar
        p bar["eventid"]
        if(bar["event_id"].to_i == eventid.to_i)
          @bar_tmp.push(bar)
        end
      }
      p @bar_tmp
      @bars = @bar_tmp
  end

  def new
    @bar = Bar.new
  end
  def edit
  end

  def create
    event_id = Event.select('id').find_by(:title => params[:title])
    p event_id
    #event_id = event_id.id

    @bar =  Bar.barAdd(bar_params,event_id)

    if @bar.save
          redirect_to event_path(title: params[:title])
    else
          render 'new'
    end
  end

  def show
    @bar = Bar.find(params[:id])

  end

  def update
      if @bar.update(bar_params)
          redirect_to event_bars_path
      else
          render 'edit'
      end
  end



  private
    def bar_params
        params[:bar].permit(:name,:url,:good,:bad,:eventid)
    end
    def set_bar
      @bar = Bar.find(params[:id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    layout 'application'
    before_action :set_event, only:[:show,:edit,:update,:destroy]
    def index
        @events = Event.where(userid: current_user.uid)

=begin
        @event_tmp = Array.new

        #ログイン中のユーザのUIDに合致するものだけ投げる
        @events.each{ |event|
          if(event["userid"] == current_user.uid)
            @event_tmp.push(event)
          end
        }
        @events = @event_tmp
        
=end
    end

    def new
        @event = Event.new
        event_date = EventDate.new
        @event.event_dates << event_date
        #@event.event_dates.build
    end

    def create
        #@event = Event.new(event_params)

        #@event =  Event.eventAdd(event_params,current_user.uid)

        event_params["userid"] = current_user.uid
        @event = Event.create(event_params)

        if @event.save
          redirect_to events_path
        else
          p "errors",@event.errors
          render :action => :new
        end
    end


    def show
      @event = Event.find_by(:title => params[:title])
      
      event_id = Event.select('id').find_by(:title => params[:title])
      puts event_id.id
      @invitee = Invitee.find_by(:event_id => event_id.id)
      
      puts @event.is_a?(Object)
      p @event
      puts @invitee.is_a?(Object)
      p @invitee
    end
    def edit
    end

    def update
        if @event.update(event_params)
            redirect_to event_path
        else
            render 'edit'
        end
    end


    private
        def event_params
            params[:event].permit(:title,:date,:detail,:userid,
            invitees_attributes:[:id,:name],
            event_dates_attributes:[:id,:event_id,:date,:good,:bad,:_destroy]
            )
        end


        def set_event
          @event = Event.find_by(title: params[:title])
        end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
      
  end
end

app/controllers/invitees_controller.rb
class InviteesController < ApplicationController
  layout 'application'
  def new
    @invitee = Invitee.new
    
  end


  def create
    @event = Event.find(params[:event_id])
    @invitee = @event.invitees.create(invitee_params)
    redirect_to event_path(@event.id)

  end

  private
    def invitee_params
      params[:invitee].permit(:name,:comment,:atendance)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  layout 'toppage'
  def login
    if user_signed_in?
      redirect_to user_root_path
    end
  end
end

app/controllers/userpages_controller.rb
class UserpagesController < ApplicationController

  def index
      @userpages = Userpage.all

      puts @userpages

=begin
      #ログイン中のユーザのUIDに合致するものだけ投げる
      @events.each{ |event|
        if(event["userid"] == current_user.uid)
          @event_tmp.push(event)
        end
      }
      @events = @event_tmp
=end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authed_helper.rb
module AuthedHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/invitee_helper.rb
module InviteeHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/bars/_form.html.erb
<%= form_for @bar,:url =>{:action => :create} do |f| %>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
        <table class="event_table">
            <tbody>
                <tr>
                  <th><%= f.label :name,"お店の名前" %></th>
                  <td><%= f.text_field :name %></td>
                </tr>
                <tr>
                  <th><%= f.label :url,"お店のWebページ" %></th>
                  <td><%= f.text_field :url %></td>
                </tr>
            </tbody>
        </table>

        <% if @bar.errors.any? %>
        <%= @bar.errors.messages[:name][0]%>
        <% end %>
        <br>
        <p>
          <%= f.submit("新しいお店を追加",:class => "btn btn-info" ) %>
        </p>

      <% end %>
    </div>
    <div class="col-sm-4">

    </div>
  </div>
</div>

app/views/bars/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/bars/index.html.erb
<h1>Event's Bars</h1>

<ul>
  <% @bars.each do |bar| %>
  <li>
    <%= link_to bar["name"],event_bar_path(bar["event_id"],bar["id"]) %>
    <%= link_to "[Edit]",edit_event_bar_path(bar["event_id"],bar["id"]) %>
    <%= link_to "[Delete]",event_bar_path(bar["event_id"],bar["id"]),method: :delete, data: { confirm: "are you sure?"} %>
  </li>
  <% end %>
</ul>



<p><%= link_to "Add New", new_event_bar_path %></p>

app/views/bars/new.html.erb
<div class="title_text">お店の候補を追加</div>

<%= render 'form' %>

app/views/bars/show.html.erb
<h1><%= @bar["name"] %></h1>

<p>
<%= @bar["url"] %>

</p>

app/views/events/_form.html.erb
<%= form_for(@event, html:{class: 'form-horizontal'}) do |f| %>
  <table class="table table-striped table-bordered">
          <tbody>
          <tr>
            <td><%= f.label :title,"イベントタイトル" %></td>
            <td><%= f.text_field :title %></td>
          </tr>

          <tr>
            <td><%= f.label :detail,"詳細" %></td>
            <td><%= f.text_area :detail %></td>
          </tr>
            <tr>
               <th>開催候補日</th>
               <th></th>
            </tr>
            <% @event.event_dates.each do |event_date| %>
              <%= f.nested_fields_for :event_dates, wrapper_tag: :tr do |q| %>
                  <td><%= q.date_field   :date,     class: 'form-control' %></td>
                  <td><%= q.remove_nested_fields_link '削除', class: 'btn btn-danger', role: 'button' %></td>
              <% end %>
            <% end %>

        </tbody>
      </table>
      <%= f.hidden_field :userid, value: current_user.uid %>
      <%= f.add_nested_fields_link :event_dates, '開催日の候補を追加する', class: 'btn btn-primary', role: 'button' %>

      <p>
        <% if @event.errors.any? %>
          <% @event.errors.full_messages.each do |error| %>
            <%= error %><br>
          <% end %>

        <% end %>

      </p>



    <p>
      <%= f.submit("新しいイベントを追加",:class => "btn btn-info" ) %>
    </p>
<% end %>

app/views/events/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="title_text">あなたのイベント一覧</div>

<div class="list-group">
  <% @events.each do |event| %>
    <%= link_to event_path(title: event.title) , :class => "list-group-item " do %>

    <h4 class="list-group-item-heading"><%= event.title %></h4>
    <p class="list-group-item-text"><%= event.detail %></p>
    <% end %>
  <% end %>
</div>

<p><%= link_to "Add New Event", new_event_path,:type => "button" ,:class => "btn btn-success" %></p>

app/views/events/new.html.erb
<div class="title_text">新しいイベントを追加</div>

<%= render 'form' %>

app/views/events/show.html.erb
<%= stylesheet_link_tag "events", :media => "all" %>

<div class="title_text"><%= @event.title %></div>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <p class="lead">参加者   <%= link_to "参加者を追加する", new_event_invitee_path(@event),{:class => "btn btn-success" , :type => "button"} %></p>


      <%= form_for @event,:url =>{:action => :create} do |f| %>
      <table class="table table-bordered eventinfo_table">
        <thead>
          <tr>

            <th>参加者名</th>
            <th>コメント</th>
            <th>参加可否</th>
            <% @event.event_dates.each do |date| %>
              <th>
                <%= date.date %>
              </th>
            <% end %>
          </tr>
        </thead>

        <tbody>

            <% @event.invitees.each do |invitee_info| %>
              <tr>

                <td><%= invitee_info.name %></td>
                <td><%= invitee_info.comment %></td>
                <td><%= invitee_info.atendance %></td>
                <% @event.event_dates.each do |date| %>
                <td>
                  <%= form_for @invitee,:url =>{:action => :create} do |form| %>
                    <div class="atendance">
                      <% invitee_true_id = "invitee_true_" + invitee_info.id.to_s + date.date.to_s %>
                      <% true_id = "true_" + invitee_info.id.to_s + date.date.to_s %>
                      <%= form.radio_button :atendance,1,:id => invitee_true_id,:checked => ""%>
                      <%= form.label true_id, "○" %>
                      <% invitee_false_id = "invitee_false_" + invitee_info.id.to_s + date.date.to_s %>
                      <% false_id = "false_" + invitee_info.id.to_s + date.date.to_s %>
                      <%= form.radio_button :atendance,2,:id => invitee_false_id %>
                      <%= form.label false_id, "×" %>
                    </div>
                  <% end %>


                </td>
                <% end %>
              </tr>
            <% end %>

        </tbody>

      </table>
      <% end %>


    </div>

  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title lead">お店候補   <%= link_to "お店候補を追加する", new_event_bar_path(@event),{:class => "btn btn-success" , :type => "button"} %></h3>
        </div>
        <div class="panel-body">
          <div class="list-group">
            <% @event.bars.each do |bar| %>
              <li>
                <%= link_to bar.name, bar.url, :class => 'list-group-item' %>
              </li>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title lead">日程候補</h3>
        </div>
        <div class="panel-body">
          <div class="list-group">
            <% @event.event_dates.each do |date| %>
              <li>
                <div class="list-group-item">
                  <%= date.date %>
                </div>
              </li>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>